CREATE DATABASE cherryh4ck;
USE cherryh4ck;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    uniqueKey VARCHAR(100) UNIQUE NOT NULL, 
    author VARCHAR(150) NOT NULL, 
    message TEXT NOT NULL, 
    sent_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message TEXT NOT NULL,
    messageId INT NOT NULL,
    sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (messageId) REFERENCES messages(id)
);